### ISSUE TITLE
ocsp.godaddy.com

### ISSUE THREAD

**Issue by don-dolarson** [cedws/apple-telemetry#31] opened 2023-07-09 13:43 UTC
When blocked, linuxmint.com can't be reached. Generating error with code SEC_ERROR_OCSP_SERVER_ERROR.

**Comment by thomasmerz** [comment] 2023-07-10 13:39
Please try using a more current/latest version because `ocsp.godaddy.com` isn't blocked anymore…

**Comment by don-dolarson** [comment] 2023-07-10 16:01
"More current/latest version" of what? I'm running behind AdGuard Home with blacklists updating itself every 24 hours. Request going to ocsp.godaddy.com, blocked by rule ocsp.godaddy.com.akadns.net which results in error above.

**Comment by thomasmerz** [comment] 2023-07-11 09:29
Ok, that clarified a lot what the problem is… Will check later after work…

**Comment by thomasmerz** [comment] 2023-07-12 07:53
Some background information on OCSP from https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol

> The Online Certificate Status Protocol (OCSP) is an [Internet](https://en.wikipedia.org/wiki/Internet) [protocol](https://en.wikipedia.org/wiki/Communication_protocol) used for obtaining the [revocation status](https://en.wikipedia.org/wiki/Revocation_status) of an [X.509](https://en.wikipedia.org/wiki/X.509) [digital certificate](https://en.wikipedia.org/wiki/Digital_certificate).[[2]](https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol#cite_note-Digital-Ocean-Tutorial-OCSP-Stapling-2) It is described in RFC 6960 and is on the [Internet standards](https://en.wikipedia.org/wiki/Internet_standard) track. It was created as an alternative to [certificate revocation lists](https://en.wikipedia.org/wiki/Certificate_revocation_list) (CRL), specifically addressing certain problems associated with using CRLs in a [public key infrastructure](https://en.wikipedia.org/wiki/Public_key_infrastructure) (PKI).[[3]](https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol#cite_note-GlobalSign-OCSP-Stapling-3) Messages communicated via OCSP are encoded in [ASN.1](https://en.wikipedia.org/wiki/ASN.1) and are usually communicated over [HTTP](https://en.wikipedia.org/wiki/HTTP). The "request/response" nature of these messages leads to OCSP [servers](https://en.wikipedia.org/wiki/Server_(computing)) being termed OCSP responders.

I agree to remove it from blacklist. PR will come…

**Comment by thomasmerz** [comment] 2023-07-12 13:06
@don-dolarson , my PR with your requested change has been merged. So this issue can be closed, can't it?

**Closed** 2023-07-13 12:34 UTC
